python = "3.10"

[node_reqs]
ComfyUI-GeometryPack = "PozzettiAndrea/ComfyUI-GeometryPack"

[cuda]
packages = ["cubvh", "sageattention", "flash-attn"]

[pypi-dependencies]
trimesh = ">=4.0.0"
omegaconf = ">=2.3.0"
einops = ">=0.8.0"
pymeshlab = "*"
timm = "*"
accelerate = ">=0.17.0"
diffusers = "*"
pytorch-lightning = "*"
rembg = "*"
huggingface_hub = "*"
scikit-image = "*"
opencv-python-headless = "*"
onnxruntime = "*"
transformers = "*"
torch = "==2.8.0"
torchvision = "==0.23.0"
torchaudio = "==2.8.0"
